//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int id { get; set; }
        public string object_name { get; set; }
        public Nullable<int> capacity_provider_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<double> amount { get; set; }
        public string currency { get; set; }
        public string comment { get; set; }
    
        public virtual CAPACITY_PROVIDER CAPACITY_PROVIDER { get; set; }
    }
}
