//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITY_PROVIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAPACITY_PROVIDER()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string contract_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
    }
}
